
import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import Navigation from "@/components/Navigation";
import Script from 'next/script';
export const metadata = {
  title: 'My first Next App',
  description: 'Generated by create next app',
  keywords: 'next,react,app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
   
      <body className={inter.className}>
     
        <Navigation />
       <div className="container mx-auto p-4">
        {children}
       </div>
       <Script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></Script>

      </body>
    </html>
  )
}
